name: Feature Request
description: Request a feature
title: "[Feature]: "
labels: [feature]
assignees:
  - taylorjdawson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Is your request related to a problem?
      description: A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Let us know about other solutions you've tried or researched.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Images? Anything that will give us more context about the feature you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
